# Generated by Django 5.2.8 on 2025-12-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_reservation_alter_chef_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date', 'created_at']},
        ),
    ]
