# Generated by Django 5.2.8 on 2025-12-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_category_options_category_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='position',
        ),
    ]
